export const GLOBAL_PHONE_CODES = [
  { name: "United States", code: "+1" },
  { name: "Afghanistan", code: "+93" },
  { name: "Albania", code: "+355" },
  { name: "Algeria", code: "+213" },
  { name: "American Samoa", code: "+1" },
  { name: "Andorra, Principality of", code: "+376" },
  { name: "Angola", code: "+244" },
  { name: "Anguilla", code: "+1" },
  { name: "Antarctica", code: "+672" },
  { name: "Antigua and Barbuda", code: "+1" },
  { name: "Argentina", code: "+54" },
  { name: "Armenia", code: "+374" },
  { name: "Aruba", code: "+297" },
  { name: "Australia", code: "+61" },
  { name: "Austria", code: "+43" },
  { name: "Azerbaijan or Azerbaidjan", code: "+994" },
  { name: "Bahamas, Commonwealth of The", code: "+1" },
  { name: "Bahrain, Kingdom of (Former Dilmun)", code: "+973" },
  { name: "Bangladesh (Former East Pakistan)", code: "+880" },
  { name: "Barbados", code: "+1" },
  { name: "Belarus", code: "+375" },
  { name: "Belgium", code: "+32" },
  { name: "Belize (Former British Honduras)", code: "+501" },
  { name: "Benin (Former Dahomey)", code: "+229" },
  { name: "Bermuda", code: "+1" },
  { name: "Bhutan, Kingdom of", code: "+975" },
  { name: "Bolivia", code: "+591" },
  { name: "Bosnia and Herzegovina", code: "+387" },
  { name: "Botswana (Former Bechuanaland)", code: "+267" },
  { name: "Brazil", code: "+55" },
  { name: "British Indian Ocean Territory (BIOT)", code: "+246" },
  { name: "Brunei (Negara Brunei Darussalam)", code: "+673" },
  { name: "Bulgaria", code: "+359" },
  { name: "Burkina Faso (Former Upper Volta)", code: "+226" },
  { name: "Burundi (Former Urundi)", code: "+257" },
  { name: "Cambodia", code: "+855" },
  { name: "Cameroon (Former French Cameroon)", code: "+237" },
  { name: "Canada", code: "+1" },
  { name: "Cape Verde", code: "+238" },
  { name: "Cayman Islands", code: "+1" },
  { name: "Central African Republic", code: "+236" },
  { name: "Chad", code: "+235" },
  { name: "Chile", code: "+56" },
  { name: "China", code: "+86" },
  { name: "Christmas Island", code: "+53" },
  { name: "Cocos (Keeling) Islands", code: "+61" },
  { name: "Colombia", code: "+57" },
  { name: "Comoros, Union of the", code: "+269" },
  { name: "Congo, Democratic Republic of the (Former Zaire)", code: "+243" },
  { name: "Congo, Republic of the", code: "+242" },
  { name: "Cook Islands (Former Harvey Islands)", code: "+682" },
  { name: "Costa Rica", code: "+506" },
  { name: "Cote D'Ivoire (Former Ivory Coast)", code: "+225" },
  { name: "Croatia (Hrvatska)", code: "+385" },
  { name: "Cuba", code: "+53" },
  { name: "Cyprus", code: "+357" },
  { name: "Czech Republic", code: "+420" },
  { name: "Czechoslavakia", code: "+421" },
  { name: "Denmark", code: "+45" },
  { name: "Djibouti", code: "+253" },
  { name: "Dominica", code: "+1" },
  { name: "Dominican Republic", code: "+1" },
  { name: "East Timor (Former Portuguese Timor)", code: "+670" },
  { name: "Ecuador", code: "+593" },
  { name: "Egypt (Former United Arab Republic - with Syria)", code: "+20" },
  { name: "El Salvador", code: "+503" },
  { name: "Equatorial Guinea (Former Spanish Guinea)", code: "+240" },
  { name: "Eritrea", code: "+291" },
  { name: "Estonia", code: "+372" },
  { name: "Ethiopia (Former Abyssinia, Italian East Africa)", code: "+251" },
  { name: "Falkland Islands (Islas Malvinas)", code: "+500" },
  { name: "Faroe Islands", code: "+298" },
  { name: "Fiji", code: "+679" },
  { name: "Finland", code: "+358" },
  { name: "France", code: "+33" },
  { name: "French Guiana or French Guyana", code: "+594" },
  { name: "French Polynesia (Former French Colony of Oceania)", code: "+689" },
  { name: "Gabon (Gabonese Republic)", code: "+241" },
  { name: "Gambia, The", code: "+220" },
  { name: "Georgia", code: "+995" },
  { name: "Germany", code: "+49" },
  { name: "Ghana", code: "+233" },
  { name: "Gibraltar", code: "+350" },
  { name: "Great Britain (United Kingdom)", code: "+44" },
  { name: "Greece", code: "+30" },
  { name: "Greenland", code: "+299" },
  { name: "Grenada", code: "+1" },
  { name: "Guadeloupe", code: "+590" },
  { name: "Guam", code: "+1" },
  { name: "Guatemala", code: "+502" },
  { name: "Guinea", code: "+224" },
  { name: "Guinea-Bissau", code: "+245" },
  { name: "Guyana", code: "+592" },
  { name: "Haiti", code: "+509" },
  { name: "Holy See (Vatican City State)", code: "+379" },
  { name: "Honduras", code: "+504" },
  { name: "Hong Kong", code: "+852" },
  { name: "Hungary", code: "+36" },
  { name: "Iceland", code: "+354" },
  { name: "India", code: "+91" },
  { name: "Indonesia", code: "+62" },
  { name: "Iran, Islamic Republic of", code: "+98" },
  { name: "Iraq", code: "+964" },
  { name: "Ireland", code: "+353" },
  { name: "Israel", code: "+972" },
  { name: "Italy", code: "+39" },
  { name: "Jamaica", code: "+1" },
  { name: "Japan", code: "+81" },
  { name: "Jordan (Former Transjordan)", code: "+962" },
  { name: "Kazakstan or Kazakhstan", code: "+7" },
  { name: "Kenya (Former British East Africa)", code: "+254" },
  { name: "Kiribati", code: "+686" },
  { name: "North Korea", code: "+850" },
  { name: "South Korea", code: "+82" },
  { name: "Kuwait", code: "+965" },
  { name: "Kyrgyzstan", code: "+996" },
  { name: "Laos", code: "+856" },
  { name: "Latvia", code: "+371" },
  { name: "Lebanon", code: "+961" },
  { name: "Lesotho (Former Basutoland)", code: "+266" },
  { name: "Liberia", code: "+231" },
  { name: "Libya (Libyan Arab Jamahiriya)", code: "+218" },
  { name: "Liechtenstein", code: "+423" },
  { name: "Lithuania", code: "+370" },
  { name: "Luxembourg", code: "+352" },
  { name: "Macau", code: "+853" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "+389" },
  { name: "Madagascar", code: "+261" },
  { name: "Malawi", code: "+265" },
  { name: "Malaysia", code: "+60" },
  { name: "Maldives", code: "+960" },
  { name: "Mali", code: "+223" },
  { name: "Malta", code: "+356" },
  { name: "Marshall Islands", code: "+692" },
  { name: "Martinique (French)", code: "+596" },
  { name: "Mauritania", code: "+222" },
  { name: "Mauritius", code: "+230" },
  { name: "Mayotte (Territorial Collectivity of Mayotte)", code: "+269" },
  { name: "Mexico", code: "+52" },
  { name: "Micronesia", code: "+691" },
  { name: "Moldova, Republic of", code: "+373" },
  { name: "Monaco, Principality of", code: "+377" },
  { name: "Mongolia", code: "+976" },
  { name: "Montserrat", code: "+1" },
  { name: "Morocco", code: "+212" },
  { name: "Mozambique", code: "+258" },
  { name: "Myanmar, Union of", code: "+95" },
  { name: "Namibia", code: "+264" },
  { name: "Nauru (Former Pleasant Island)", code: "+674" },
  { name: "Nepal", code: "+977" },
  { name: "Netherlands", code: "+31" },
  { name: "Netherlands Antilles", code: "+599" },
  { name: "New Caledonia", code: "+687" },
  { name: "New Zealand (Aotearoa)", code: "+64" },
  { name: "Nicaragua", code: "+505" },
  { name: "Niger", code: "+227" },
  { name: "Nigeria", code: "+234" },
  { name: "Niue (Former Savage Island)", code: "+683" },
  { name: "Norfolk Island", code: "+672" },
  { name: "Northern Mariana Islands", code: "+1" },
  { name: "Norway", code: "+47" },
  { name: "Oman, Sultanate of (Former Muscat and Oman)", code: "+968" },
  { name: "Pakistan (Former West Pakistan)", code: "+92" },
  { name: "Palau", code: "+680" },
  { name: "Palestinian State (Proposed)", code: "+970" },
  { name: "Panama", code: "+507" },
  { name: "Papua New Guinea", code: "+675" },
  { name: "Paraguay", code: "+595" },
  { name: "Peru", code: "+51" },
  { name: "Philippines", code: "+63" },
  { name: "Pitcairn Island", code: "+64" },
  { name: "Poland", code: "+48" },
  { name: "Portugal", code: "+351" },
  { name: "Puerto Rico", code: "+1" },
  { name: "Qatar, State of", code: "+974" },
  { name: "Reunion (French) (Former Bourbon Island)", code: "+262" },
  { name: "Romania", code: "+40" },
  { name: "Russian Federation", code: "+7" },
  { name: "Rwanda (Rwandese Republic) (Former Ruanda)", code: "+250" },
  { name: "Saint Helena", code: "+290" },
  { name: "Saint Kitts and Nevis", code: "+1" },
  { name: "Saint Lucia", code: "+1" },
  { name: "Saint Pierre and Miquelon", code: "+508" },
  { name: "Saint Vincent and the Grenadines", code: "+1" },
  { name: "Samoa (Former Western Samoa)", code: "+685" },
  { name: "San Marino", code: "+378" },
  { name: "Sao Tome and Principe", code: "+239" },
  { name: "Saudi Arabia", code: "+966" },
  { name: "Serbia, Republic of", code: "+381" },
  { name: "Senegal", code: "+221" },
  { name: "Seychelles", code: "+248" },
  { name: "Sierra Leone", code: "+232" },
  { name: "Singapore", code: "+65" },
  { name: "Slovakia", code: "+421" },
  { name: "Slovenia", code: "+386" },
  { name: "Solomon Islands", code: "+677" },
  { name: "Somalia", code: "+252" },
  { name: "South Africa", code: "+27" },
  { name: "Spain", code: "+34" },
  { name: "Sri Lanka", code: "+94" },
  { name: "Sudan", code: "+249" },
  { name: "Suriname", code: "+597" },
  { name: "Svalbard", code: "+47" },
  { name: "Swaziland, Kingdom of", code: "+268" },
  { name: "Sweden", code: "+46" },
  { name: "Switzerland", code: "+41" },
  { name: "Syria", code: "+963" },
  { name: "Taiwan", code: "+886" },
  { name: "Tajikistan", code: "+992" },
  { name: "Tanzania, United Republic of", code: "+255" },
  { name: "Thailand (Former Siam)", code: "+66" },
  { name: "Togo (Former French Togoland)", code: "+228" },
  { name: "Tokelau", code: "+690" },
  { name: "Tonga, Kingdom of (Former Friendly Islands)", code: "+676" },
  { name: "Trinidad and Tobago", code: "+1" },
  { name: "Tunisia", code: "+216" },
  { name: "Turkey", code: "+90" },
  { name: "Turkmenistan", code: "+993" },
  { name: "Turks and Caicos Islands", code: "+1" },
  { name: "Tuvalu (Former Ellice Islands)", code: "+688" },
  { name: "Uganda, Republic of", code: "+256" },
  { name: "Ukraine", code: "+380" },
  { name: "United Arab Emirates (UAE)", code: "+971" },
  { name: "United Kingdom", code: "+44" },
  { name: "Uruguay", code: "+598" },
  { name: "Uzbekistan", code: "+998" },
  { name: "Vanuatu (Former New Hebrides)", code: "+678" },
  { name: "Vatican City State (Holy See)", code: "+418" },
  { name: "Venezuela", code: "+58" },
  { name: "Vietnam", code: "+84" },
  { name: "Virgin Islands, British", code: "+1" },
  { name: "Virgin Islands, United States", code: "+1" },
  { name: "Wallis and Futuna Islands", code: "+681" },
  { name: "Yemen", code: "+967" },
  { name: "Zambia, Republic of", code: "+260" },
  { name: "Zimbabwe, Republic of", code: "+263" },
];
