export const phoneLADA = ref([
    { name: '+1', iso_code: 'US', code: 'United States' },
    { name: '+1', iso_code: 'CA', code: 'Canada' },
    { name: '+7', iso_code: 'RU', code: 'Russian Federation' },
    { name: '+7', iso_code: 'KZ', code: 'Kazakhstan' },
    { name: '+20', iso_code: 'EG', code: 'Egypt' },
    { name: '+27', iso_code: 'ZA', code: 'South Africa' },
    { name: '+30', iso_code: 'GR', code: 'Greece' },
    { name: '+31', iso_code: 'NL', code: 'Netherlands' },
    { name: '+32', iso_code: 'BE', code: 'Belgium' },
    { name: '+33', iso_code: 'FR', code: 'France' },
    { name: '+34', iso_code: 'ES', code: 'Spain' },
    { name: '+36', iso_code: 'HU', code: 'Hungary' },
    { name: '+39', iso_code: 'IT', code: 'Italy' },
    { name: '+40', iso_code: 'RO', code: 'Romania' },
    { name: '+41', iso_code: 'CH', code: 'Switzerland' },
    { name: '+43', iso_code: 'AT', code: 'Austria' },
    { name: '+44', iso_code: 'GB', code: 'United Kingdom' },
    { name: '+45', iso_code: 'DK', code: 'Denmark' },
    { name: '+46', iso_code: 'SE', code: 'Sweden' },
    { name: '+47', iso_code: 'NO', code: 'Norway' },
    { name: '+48', iso_code: 'PL', code: 'Poland' },
    { name: '+49', iso_code: 'DE', code: 'Germany' },
    { name: '+51', iso_code: 'PE', code: 'Peru' },
    { name: '+52', iso_code: 'MX', code: 'Mexico' },
    { name: '+53', iso_code: 'CU', code: 'Cuba' },
    { name: '+54', iso_code: 'AR', code: 'Argentina' },
    { name: '+55', iso_code: 'BR', code: 'Brazil' },
    { name: '+56', iso_code: 'CL', code: 'Chile' },
    { name: '+57', iso_code: 'CO', code: 'Colombia' },
    { name: '+58', iso_code: 'VE', code: 'Venezuela, Bolivarian Republic of' },
    { name: '+60', iso_code: 'MY', code: 'Malaysia' },
    { name: '+61', iso_code: 'AU', code: 'Australia' },
    { name: '+62', iso_code: 'ID', code: 'Indonesia' },
    { name: '+63', iso_code: 'PH', code: 'Philippines' },
    { name: '+64', iso_code: 'NZ', code: 'New Zealand' },
    { name: '+65', iso_code: 'SG', code: 'Singapore' },
    { name: '+66', iso_code: 'TH', code: 'Thailand' },
    { name: '+81', iso_code: 'JP', code: 'Japan' },
    { name: '+82', iso_code: 'KR', code: 'Korea, Republic of' },
    { name: '+84', iso_code: 'VN', code: 'Viet Nam' },
    { name: '+86', iso_code: 'CN', code: 'China' },
    { name: '+90', iso_code: 'TR', code: 'Turkey' },
    { name: '+91', iso_code: 'IN', code: 'India' },
    { name: '+92', iso_code: 'PK', code: 'Pakistan' },
    { name: '+93', iso_code: 'AF', code: 'Afghanistan' },
    { name: '+94', iso_code: 'LK', code: 'Sri Lanka' },
    { name: '+95', iso_code: 'MM', code: 'Myanmar' },
    { name: '+98', iso_code: 'IR', code: 'Iran, Islamic Republic of' },
    { name: '+211', iso_code: 'SS', code: 'South Sudan' },
    { name: '+212', iso_code: 'MA', code: 'Morocco' },
    { name: '+213', iso_code: 'DZ', code: 'Algeria' },
    { name: '+216', iso_code: 'TN', code: 'Tunisia' },
    { name: '+218', iso_code: 'LY', code: 'Libya' },
    { name: '+220', iso_code: 'GM', code: 'Gambia' },
    { name: '+221', iso_code: 'SN', code: 'Senegal' },
    { name: '+222', iso_code: 'MR', code: 'Mauritania' },
    { name: '+223', iso_code: 'ML', code: 'Mali' },
    { name: '+224', iso_code: 'GN', code: 'Guinea' },
    { name: '+225', iso_code: 'CI', code: 'Côte dIvoire' },
    { name: '+226', iso_code: 'BF', code: 'Burkina Faso' },
    { name: '+227', iso_code: 'NE', code: 'Niger' },
    { name: '+228', iso_code: 'TG', code: 'Togo' },
    { name: '+229', iso_code: 'BJ', code: 'Benin' },
    { name: '+230', iso_code: 'MU', code: 'Mauritius' },
    { name: '+231', iso_code: 'LR', code: 'Liberia' },
    { name: '+232', iso_code: 'SL', code: 'Sierra Leone' },
    { name: '+233', iso_code: 'GH', code: 'Ghana' },
    { name: '+234', iso_code: 'NG', code: 'Nigeria' },
    { name: '+235', iso_code: 'TD', code: 'Chad' },
    { name: '+236', iso_code: 'CF', code: 'Central African Republic' },
    { name: '+237', iso_code: 'CM', code: 'Cameroon' },
    { name: '+238', iso_code: 'CV', code: 'Cabo Verde' },
    { name: '+239', iso_code: 'ST', code: 'Sao Tome and Principe' },
    { name: '+240', iso_code: 'GQ', code: 'Equatorial Guinea' },
    { name: '+241', iso_code: 'GA', code: 'Gabon' },
    { name: '+242', iso_code: 'CG', code: 'Congo' },
    { name: '+243', iso_code: 'CD', code: 'Congo, The Democratic Republic of the' },
    { name: '+244', iso_code: 'AO', code: 'Angola' },
    { name: '+245', iso_code: 'GW', code: 'Guinea-Bissau' },
    { name: '+246', iso_code: 'IO', code: 'British Indian Ocean Territory' },
    { name: '+248', iso_code: 'SC', code: 'Seychelles' },
    { name: '+249', iso_code: 'SD', code: 'Sudan' },
    { name: '+250', iso_code: 'RW', code: 'Rwanda' },
    { name: '+251', iso_code: 'ET', code: 'Ethiopia' },
    { name: '+252', iso_code: 'SO', code: 'Somalia' },
    { name: '+253', iso_code: 'DJ', code: 'Djibouti' },
    { name: '+254', iso_code: 'KE', code: 'Kenya' },
    { name: '+255', iso_code: 'TZ', code: 'Tanzania, United Republic of' },
    { name: '+256', iso_code: 'UG', code: 'Uganda' },
    { name: '+257', iso_code: 'BI', code: 'Burundi' },
    { name: '+258', iso_code: 'MZ', code: 'Mozambique' },
    { name: '+260', iso_code: 'ZM', code: 'Zambia' },
    { name: '+261', iso_code: 'MG', code: 'Madagascar' },
    { name: '+262', iso_code: 'RE', code: 'Réunion' },
    { name: '+263', iso_code: 'ZW', code: 'Zimbabwe' },
    { name: '+264', iso_code: 'NA', code: 'Namibia' },
    { name: '+265', iso_code: 'MW', code: 'Malawi' },
    { name: '+266', iso_code: 'LS', code: 'Lesotho' },
    { name: '+267', iso_code: 'BW', code: 'Botswana' },
    { name: '+268', iso_code: 'SZ', code: 'Eswatini' },
    { name: '+269', iso_code: 'KM', code: 'Comoros' },
    { name: '+290', iso_code: 'SH', code: 'Saint Helena, Ascension and Tristan da Cunha' },
    { name: '+291', iso_code: 'ER', code: 'Eritrea' },
    { name: '+297', iso_code: 'AW', code: 'Aruba' },
    { name: '+298', iso_code: 'FO', code: 'Faroe Islands' },
    { name: '+299', iso_code: 'GL', code: 'Greenland' },
    { name: '+350', iso_code: 'GI', code: 'Gibraltar' },
    { name: '+351', iso_code: 'PT', code: 'Portugal' },
    { name: '+352', iso_code: 'LU', code: 'Luxembourg' },
    { name: '+353', iso_code: 'IE', code: 'Ireland' },
    { name: '+354', iso_code: 'IS', code: 'Iceland' },
    { name: '+355', iso_code: 'AL', code: 'Albania' },
    { name: '+356', iso_code: 'MT', code: 'Malta' },
    { name: '+357', iso_code: 'CY', code: 'Cyprus' },
    { name: '+358', iso_code: 'FI', code: 'Finland' },
    { name: '+359', iso_code: 'BG', code: 'Bulgaria' },
    { name: '+370', iso_code: 'LT', code: 'Lithuania' },
    { name: '+371', iso_code: 'LV', code: 'Latvia' },
    { name: '+372', iso_code: 'EE', code: 'Estonia' },
    { name: '+373', iso_code: 'MD', code: 'Moldova, Republic of' },
    { name: '+374', iso_code: 'AM', code: 'Armenia' },
    { name: '+375', iso_code: 'BY', code: 'Belarus' },
    { name: '+376', iso_code: 'AD', code: 'Andorra' },
    { name: '+377', iso_code: 'MC', code: 'Monaco' },
    { name: '+378', iso_code: 'SM', code: 'San Marino' },
    { name: '+379', iso_code: 'VA', code: 'Holy See (Vatican City State)' },
    { name: '+380', iso_code: 'UA', code: 'Ukraine' },
    { name: '+381', iso_code: 'RS', code: 'Serbia' },
    { name: '+382', iso_code: 'ME', code: 'Montenegro' },
    { name: '+383', iso_code: 'XK', code: 'XK' },
    { name: '+385', iso_code: 'HR', code: 'Croatia' },
    { name: '+386', iso_code: 'SI', code: 'Slovenia' },
    { name: '+387', iso_code: 'BA', code: 'Bosnia and Herzegovina' },
    { name: '+389', iso_code: 'MK', code: 'North Macedonia' },
    { name: '+420', iso_code: 'CZ', code: 'Czechia' },
    { name: '+421', iso_code: 'SK', code: 'Slovakia' },
    { name: '+423', iso_code: 'LI', code: 'Liechtenstein' },
    { name: '+500', iso_code: 'FK', code: 'Falkland Islands (Malvinas)' },
    { name: '+501', iso_code: 'BZ', code: 'Belize' },
    { name: '+502', iso_code: 'GT', code: 'Guatemala' },
    { name: '+503', iso_code: 'SV', code: 'El Salvador' },
    { name: '+504', iso_code: 'HN', code: 'Honduras' },
    { name: '+505', iso_code: 'NI', code: 'Nicaragua' },
    { name: '+506', iso_code: 'CR', code: 'Costa Rica' },
    { name: '+507', iso_code: 'PA', code: 'Panama' },
    { name: '+508', iso_code: 'PM', code: 'Saint Pierre and Miquelon' },
    { name: '+509', iso_code: 'HT', code: 'Haiti' },
    { name: '+590', iso_code: 'GP', code: 'Guadeloupe' },
    { name: '+591', iso_code: 'BO', code: 'Bolivia, Plurinational State of' },
    { name: '+592', iso_code: 'GY', code: 'Guyana' },
    { name: '+593', iso_code: 'EC', code: 'Ecuador' },
    { name: '+594', iso_code: 'GF', code: 'French Guiana' },
    { name: '+595', iso_code: 'PY', code: 'Paraguay' },
    { name: '+596', iso_code: 'MQ', code: 'Martinique' },
    { name: '+597', iso_code: 'SR', code: 'Suriname' }
]);